version: 2

workflows:
  version: 2
  main:
    jobs:
      - build
      - lint

jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: |
          uname -a
          which node
          node -v
          which yarn
          yarn -v
      - run: |
          yarn link
          cd example
          yarn link "vuepress-theme-blogue"
          yarn install
          yarn run build
  lint:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: yarn install -D
      - run: yarn lint
