version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - run: pwd && ls -a
      - run: which node && node -v
      - run: which yarn && yarn -v
      - run: yarn link
      - run: cd example
      - run: yarn link "vuepress-theme-blogue"
      - run: yarn install
      - run: yarn run build
