version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run: pwd && ls -a
      - run: which node && node -v
      - run: which yarn && yarn -v
      - run: yarn link
      - run: |
          cd example
          yarn link "vuepress-theme-blogue"
          yarn install
          pwd && ls -a && cat package.json
          yarn run build
