name: main

on: push

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        # Reinstall node modules even if `cache-hit` is `true` because we need to build symlinks for Yarn workspace
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn link
          cd example
          yarn link "vuepress-theme-blogue"
          yarn install
          yarn run build
